name: 'Mirror to GitHub'
branding:
  icon: 'download-cloud'
  color: 'white'
description: 'Mirror a repository to GitHub'
inputs:
  origin:
    description: 'URL of remote git repository'
    required: true
  SOURCE_GITHUB_TOKEN:
    description: 'Token used to read the remote repo to mirror'
    required: true
  TARGET_GITHUB_TOKEN:
    description: 'Token used to update the current/target repository'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.origin }}
  env:
    SOURCE_GITHUB_TOKEN: ${{ inputs.SOURCE_GITHUB_TOKEN }}
    TARGET_GITHUB_TOKEN: ${{ inputs.TARGET_GITHUB_TOKEN }}
